// jiaxin-room-next/src/app/(auth)/register/page.tsx
"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { get, post } from "@/lib/api";

export default function RegisterPage() {
  const router = useRouter();
  const [username, setUsername] = useState("");
  const [studentId, setStudentId] = useState("");
  const [realName, setRealName] = useState("");
  const [email, setEmail] = useState("");
  const [emailCode, setEmailCode] = useState("");
  const [password, setPassword] = useState("");
  const [sending, setSending] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function sendEmailCode() {
    if (!email.trim()) {
      setError("请先填写邮箱");
      return;
    }
    setSending(true);
    setError(null);
    try {
      const res = await get<{ sent?: boolean }>("/user/email/code", { email });
      if (res.code !== 1) {
        setError(res.msg || "发送失败");
      }
    } catch {
      setError("发送失败，请稍后重试");
    } finally {
      setSending(false);
    }
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    setLoading(true);
    try {
      const res = await post("/user/register", {
        username,
        studentId,
        realName,
        email,
        emailCode,
        password,
      });
      if (res.code !== 1) {
        setError(res.msg || "注册失败");
        setLoading(false);
        return;
      }
      router.push("/login");
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "网络错误");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="relative flex min-h-screen items-center justify-center bg-gradient-to-br from-[var(--color-primary-pale)] via-[var(--color-bg)] to-[var(--color-bg-secondary)] px-4 py-12">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_70%_50%_at_50%_-10%,rgba(0,113,227,0.08),transparent)]" />
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4, ease: [0.25, 0.46, 0.45, 0.94] }}
        className="relative w-full max-w-lg"
      >
        <Card className="border-[var(--color-border-light)] bg-[var(--color-surface)]/95 shadow-[var(--shadow-xl)] backdrop-blur-md">
          <CardHeader className="space-y-1 pb-6 text-center">
            <CardTitle className="text-2xl font-semibold">创建账号</CardTitle>
            <p className="text-sm text-[var(--color-text-secondary)]">
              加入夹心 Room，开始预约你的练琴时间
            </p>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-4">
              {error ? (
                <p className="rounded-[var(--radius-md)] bg-[var(--color-danger-bg)] px-3 py-2 text-sm text-[var(--color-danger)]">
                  {error}
                </p>
              ) : null}
              <div className="space-y-2">
                <label className="text-sm font-medium" htmlFor="reg-username">
                  用户名
                </label>
                <Input
                  id="reg-username"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  required
                  autoComplete="username"
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium" htmlFor="studentId">
                  学号
                </label>
                <Input
                  id="studentId"
                  value={studentId}
                  onChange={(e) => setStudentId(e.target.value)}
                  placeholder="选填"
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium" htmlFor="realName">
                  真实姓名
                </label>
                <Input
                  id="realName"
                  value={realName}
                  onChange={(e) => setRealName(e.target.value)}
                  required
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium" htmlFor="email">
                  邮箱
                </label>
                <div className="flex gap-2">
                  <Input
                    id="email"
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    required
                    className="flex-1"
                  />
                  <Button
                    type="button"
                    variant="outline"
                    className="shrink-0"
                    disabled={sending}
                    onClick={sendEmailCode}
                  >
                    {sending ? "发送中" : "发送验证码"}
                  </Button>
                </div>
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium" htmlFor="emailCode">
                  邮箱验证码
                </label>
                <Input
                  id="emailCode"
                  value={emailCode}
                  onChange={(e) => setEmailCode(e.target.value)}
                  placeholder="请输入邮箱中的验证码"
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium" htmlFor="reg-password">
                  密码
                </label>
                <Input
                  id="reg-password"
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                  minLength={6}
                  autoComplete="new-password"
                />
              </div>
              <Button type="submit" className="mt-2 h-11 w-full" disabled={loading}>
                {loading ? "提交中…" : "注册"}
              </Button>
            </form>
            <p className="mt-6 text-center text-sm text-[var(--color-text-secondary)]">
              已有账号？{" "}
              <Link href="/login" className="font-medium text-[var(--color-primary)] hover:underline">
                返回登录
              </Link>
            </p>
          </CardContent>
        </Card>
      </motion.div>
    </div>
  );
}

// piano-room-vue3/src/views/auth/Register.vue
<template>
  <div class="auth-page">
    <div class="back-btn" @click="router.push('/login')">
      <el-icon><ArrowLeft /></el-icon>
      <span>返回登录</span>
    </div>
    <div class="auth-card">
      <div class="auth-header">
        <el-icon size="36" color="#409eff"><Headset /></el-icon>
        <h2>注册账号</h2>
      </div>
      <el-form ref="formRef" :model="form" :rules="rules" label-position="top" @keyup.enter="handleRegister">
        <el-form-item label="用户名" prop="username">
          <el-input v-model="form.username" placeholder="请输入用户名" clearable />
        </el-form-item>
        <el-form-item label="真实姓名" prop="realName">
          <el-input v-model="form.realName" placeholder="请输入真实姓名" clearable />
        </el-form-item>
        <el-form-item label="学号" prop="studentId">
          <el-input v-model="form.studentId" placeholder="请输入学号" clearable />
        </el-form-item>
        <el-form-item label="邮箱" prop="email">
          <div class="email-row">
            <el-input v-model="form.email" placeholder="请输入邮箱" clearable />
            <el-button :disabled="emailCooldown > 0" @click="sendEmailCode">
              {{ emailCooldown > 0 ? `${emailCooldown}s` : '获取验证码' }}
            </el-button>
          </div>
        </el-form-item>
        <el-form-item label="邮箱验证码" prop="emailCode">
          <el-input v-model="form.emailCode" placeholder="请输入邮箱验证码" clearable />
        </el-form-item>
        <el-form-item label="密码" prop="password">
          <el-input v-model="form.password" type="password" placeholder="请输入密码" show-password clearable />
        </el-form-item>
        <el-form-item label="图形验证码" prop="captchaCode">
          <div class="captcha-row">
            <el-input v-model="form.captchaCode" placeholder="请输入图形验证码" clearable />
            <img :src="captchaUrl" class="captcha-img" @click="loadCaptcha" />
          </div>
        </el-form-item>
        <el-button type="primary" :loading="loading" class="submit-btn" @click="handleRegister">注册</el-button>
      </el-form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, type FormInstance, type FormRules } from 'element-plus'
import { userApi } from '@/api/user'

const router = useRouter()
const formRef = ref<FormInstance>()
const loading = ref(false)
const captchaUrl = ref('')
const emailCooldown = ref(0)

const form = ref({
  username: '',
  realName: '',
  studentId: '',
  email: '',
  emailCode: '',
  password: '',
  captchaCode: '',
})

const rules: FormRules = {
  username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
  realName: [{ required: true, message: '请输入真实姓名', trigger: 'blur' }],
  email: [{ required: true, type: 'email', message: '请输入正确的邮箱', trigger: 'blur' }],
  emailCode: [{ required: true, message: '请输入邮箱验证码', trigger: 'blur' }],
  password: [{ required: true, min: 6, message: '密码至少6位', trigger: 'blur' }],
  captchaCode: [{ required: true, message: '请输入图形验证码', trigger: 'blur' }],
}

async function loadCaptcha() {
  const res = await userApi.getCaptcha(1)
  if (res?.code === 1) captchaUrl.value = res.data
}

async function sendEmailCode() {
  if (!form.value.email) { ElMessage.warning('请先输入邮箱'); return }
  await userApi.sendEmailCode(form.value.email, 0)
  ElMessage.success('验证码已发送')
  emailCooldown.value = 60
  const timer = setInterval(() => {
    emailCooldown.value--
    if (emailCooldown.value <= 0) clearInterval(timer)
  }, 1000)
}

async function handleRegister() {
  await formRef.value?.validate(async (valid) => {
    if (!valid) return
    loading.value = true
    try {
      const res = await userApi.register(form.value as any)
      if (res?.code === 1) {
        ElMessage.success('注册成功，请登录')
        router.push('/login')
      } else {
        ElMessage.error(res?.msg || '注册失败')
        loadCaptcha()
      }
    } finally {
      loading.value = false
    }
  })
}

onMounted(() => loadCaptcha())
</script>

<style scoped>
.auth-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
  position: relative;
  padding: 40px 16px;
}
.back-btn {
  position: absolute;
  top: 24px;
  left: 24px;
  display: flex;
  align-items: center;
  gap: 6px;
  color: rgba(255,255,255,0.7);
  cursor: pointer;
  font-size: 14px;
  padding: 8px 16px;
  border-radius: 20px;
  background: rgba(255,255,255,0.1);
  transition: all 0.2s;
}
.back-btn:hover { background: rgba(255,255,255,0.2); color: #fff; }
.auth-card {
  width: 420px;
  background: #fff;
  border-radius: 16px;
  padding: 40px;
  box-shadow: 0 20px 60px rgba(0,0,0,0.4);
}
.auth-header {
  text-align: center;
  margin-bottom: 28px;
}
.auth-header h2 { font-size: 20px; margin-top: 10px; }
.email-row, .captcha-row {
  display: flex;
  gap: 10px;
  align-items: center;
}
.captcha-img {
  height: 38px;
  border-radius: 6px;
  cursor: pointer;
  border: 1px solid #dcdfe6;
  flex-shrink: 0;
}
.submit-btn { width: 100%; margin-top: 8px; }
@media (max-width: 480px) {
  .auth-card { width: calc(100vw - 32px); padding: 28px 20px; }
}
</style>
