// jiaxin-room-next/src/app/(admin)/admin/settings/page.tsx
"use client";

import { useCallback, useEffect, useState } from "react";
import * as Tabs from "@radix-ui/react-tabs";
import { motion } from "framer-motion";
import { Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { get, post } from "@/lib/api";
import { cn } from "@/lib/utils";

interface BasicSetting {
  systemName: string;
  description: string;
  copyright: string;
  slotStartHour: number;
  slotEndHour: number;
  slotDurationMinutes: number;
}

interface ReservationSetting {
  maxAdvanceDays: number;
  signInGrace: number;
  maxNoShow: number;
}

interface SecuritySetting {
  tokenExpireHours: number;
  minPasswordLength: number;
}

export default function AdminSettingsPage() {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState<string | null>(null);
  const [msg, setMsg] = useState<string | null>(null);
  const [err, setErr] = useState<string | null>(null);

  const [basic, setBasic] = useState<BasicSetting>({
    systemName: "",
    description: "",
    copyright: "",
    slotStartHour: 8,
    slotEndHour: 22,
    slotDurationMinutes: 60,
  });

  const [reservation, setReservation] = useState<ReservationSetting>({
    maxAdvanceDays: 7,
    signInGrace: 15,
    maxNoShow: 3,
  });

  const [security, setSecurity] = useState<SecuritySetting>({
    tokenExpireHours: 24,
    minPasswordLength: 6,
  });

  const load = useCallback(async () => {
    setLoading(true);
    setErr(null);
    try {
      const [b, r, s] = await Promise.all([
        get<BasicSetting>("/system/settings/basic"),
        get<ReservationSetting>("/system/settings/reservation"),
        get<SecuritySetting>("/system/settings/security"),
      ]);
      if (b.code === 1 && b.data) setBasic((prev) => ({ ...prev, ...b.data }));
      if (r.code === 1 && r.data) setReservation((prev) => ({ ...prev, ...r.data }));
      if (s.code === 1 && s.data) setSecurity((prev) => ({ ...prev, ...s.data }));
    } catch {
      setErr("加载设置失败");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  async function saveBasic(e: React.FormEvent) {
    e.preventDefault();
    setSaving("basic");
    setMsg(null);
    setErr(null);
    try {
      const res = await post("/system/settings/basic", basic);
      if (res.code === 1) setMsg("基础设置已保存");
      else setErr(res.msg || "保存失败");
    } catch {
      setErr("保存失败");
    } finally {
      setSaving(null);
    }
  }

  async function saveReservation(e: React.FormEvent) {
    e.preventDefault();
    setSaving("reservation");
    setMsg(null);
    setErr(null);
    try {
      const res = await post("/system/settings/reservation", reservation);
      if (res.code === 1) setMsg("预约设置已保存");
      else setErr(res.msg || "保存失败");
    } catch {
      setErr("保存失败");
    } finally {
      setSaving(null);
    }
  }

  async function saveSecurity(e: React.FormEvent) {
    e.preventDefault();
    setSaving("security");
    setMsg(null);
    setErr(null);
    try {
      const res = await post("/system/settings/security", security);
      if (res.code === 1) setMsg("安全设置已保存");
      else setErr(res.msg || "保存失败");
    } catch {
      setErr("保存失败");
    } finally {
      setSaving(null);
    }
  }

  if (loading) {
    return (
      <div className="flex min-h-[40vh] items-center justify-center">
        <Loader2 className="size-8 animate-spin text-[var(--color-primary)]" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <motion.div initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="text-xl font-semibold tracking-tight text-[var(--color-text)]">
          系统设置
        </h1>
        <p className="mt-1 text-sm text-[var(--color-text-secondary)]">
          分模块保存，互不影响
        </p>
      </motion.div>

      {msg ? (
        <p className="rounded-[var(--radius-md)] bg-[var(--color-success-bg)] px-3 py-2 text-sm text-[var(--color-success)]">
          {msg}
        </p>
      ) : null}
      {err ? (
        <p className="rounded-[var(--radius-md)] bg-[var(--color-danger-bg)] px-3 py-2 text-sm text-[var(--color-danger)]">
          {err}
        </p>
      ) : null}

      <Tabs.Root defaultValue="basic" className="space-y-6">
        <Tabs.List className="flex flex-wrap gap-2 rounded-[var(--radius-lg)] border border-[var(--color-border-light)] bg-white p-1 shadow-[var(--shadow-sm)]">
          {[
            { id: "basic", label: "基础设置" },
            { id: "reservation", label: "预约设置" },
            { id: "security", label: "安全设置" },
          ].map((t) => (
            <Tabs.Trigger
              key={t.id}
              value={t.id}
              className={cn(
                "rounded-[var(--radius-md)] px-4 py-2 text-sm font-medium transition-colors",
                "text-[var(--color-text-secondary)] hover:text-[var(--color-text)]",
                "data-[state=active]:bg-[var(--color-primary-light)] data-[state=active]:text-[var(--color-primary)]"
              )}
            >
              {t.label}
            </Tabs.Trigger>
          ))}
        </Tabs.List>

        <Tabs.Content value="basic">
          <Card className="border-[var(--color-border-light)] bg-white shadow-[var(--shadow-card)]">
            <CardHeader>
              <CardTitle>基础设置</CardTitle>
              <CardDescription>系统名称、版权与开放时段</CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={saveBasic} className="max-w-xl space-y-4">
                <div className="space-y-1.5">
                  <label className="text-sm font-medium">系统名称</label>
                  <Input
                    value={basic.systemName}
                    onChange={(e) =>
                      setBasic((b) => ({ ...b, systemName: e.target.value }))
                    }
                    required
                  />
                </div>
                <div className="space-y-1.5">
                  <label className="text-sm font-medium">简介</label>
                  <textarea
                    className="min-h-[88px] w-full rounded-[var(--radius-sm)] border border-[var(--color-border)] bg-white px-3 py-2 text-sm focus:border-[var(--color-primary)] focus:outline-none focus:ring-2 focus:ring-[var(--color-primary)]/15"
                    value={basic.description}
                    onChange={(e) =>
                      setBasic((b) => ({ ...b, description: e.target.value }))
                    }
                  />
                </div>
                <div className="space-y-1.5">
                  <label className="text-sm font-medium">版权信息</label>
                  <Input
                    value={basic.copyright}
                    onChange={(e) =>
                      setBasic((b) => ({ ...b, copyright: e.target.value }))
                    }
                  />
                </div>
                <div className="grid gap-4 sm:grid-cols-3">
                  <div className="space-y-1.5">
                    <label className="text-sm font-medium">开始小时</label>
                    <Input
                      type="number"
                      min={0}
                      max={23}
                      value={basic.slotStartHour}
                      onChange={(e) =>
                        setBasic((b) => ({
                          ...b,
                          slotStartHour: Number(e.target.value),
                        }))
                      }
                    />
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-sm font-medium">结束小时</label>
                    <Input
                      type="number"
                      min={0}
                      max={23}
                      value={basic.slotEndHour}
                      onChange={(e) =>
                        setBasic((b) => ({
                          ...b,
                          slotEndHour: Number(e.target.value),
                        }))
                      }
                    />
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-sm font-medium">时段时长（分钟）</label>
                    <Input
                      type="number"
                      min={15}
                      step={5}
                      value={basic.slotDurationMinutes}
                      onChange={(e) =>
                        setBasic((b) => ({
                          ...b,
                          slotDurationMinutes: Number(e.target.value),
                        }))
                      }
                    />
                  </div>
                </div>
                <Button type="submit" disabled={saving === "basic"}>
                  {saving === "basic" ? "保存中…" : "保存基础设置"}
                </Button>
              </form>
            </CardContent>
          </Card>
        </Tabs.Content>

        <Tabs.Content value="reservation">
          <Card className="border-[var(--color-border-light)] bg-white shadow-[var(--shadow-card)]">
            <CardHeader>
              <CardTitle>预约设置</CardTitle>
              <CardDescription>提前预约、签到宽限与爽约规则</CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={saveReservation} className="max-w-xl space-y-4">
                <div className="space-y-1.5">
                  <label className="text-sm font-medium">最长提前预约（天）</label>
                  <Input
                    type="number"
                    min={1}
                    value={reservation.maxAdvanceDays}
                    onChange={(e) =>
                      setReservation((r) => ({
                        ...r,
                        maxAdvanceDays: Number(e.target.value),
                      }))
                    }
                  />
                </div>
                <div className="space-y-1.5">
                  <label className="text-sm font-medium">签到宽限（分钟）</label>
                  <Input
                    type="number"
                    min={0}
                    value={reservation.signInGrace}
                    onChange={(e) =>
                      setReservation((r) => ({
                        ...r,
                        signInGrace: Number(e.target.value),
                      }))
                    }
                  />
                </div>
                <div className="space-y-1.5">
                  <label className="text-sm font-medium">最大爽约次数</label>
                  <Input
                    type="number"
                    min={0}
                    value={reservation.maxNoShow}
                    onChange={(e) =>
                      setReservation((r) => ({
                        ...r,
                        maxNoShow: Number(e.target.value),
                      }))
                    }
                  />
                </div>
                <Button type="submit" disabled={saving === "reservation"}>
                  {saving === "reservation" ? "保存中…" : "保存预约设置"}
                </Button>
              </form>
            </CardContent>
          </Card>
        </Tabs.Content>

        <Tabs.Content value="security">
          <Card className="border-[var(--color-border-light)] bg-white shadow-[var(--shadow-card)]">
            <CardHeader>
              <CardTitle>安全设置</CardTitle>
              <CardDescription>令牌与密码策略</CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={saveSecurity} className="max-w-xl space-y-4">
                <div className="space-y-1.5">
                  <label className="text-sm font-medium">Token 有效期（小时）</label>
                  <Input
                    type="number"
                    min={1}
                    value={security.tokenExpireHours}
                    onChange={(e) =>
                      setSecurity((s) => ({
                        ...s,
                        tokenExpireHours: Number(e.target.value),
                      }))
                    }
                  />
                </div>
                <div className="space-y-1.5">
                  <label className="text-sm font-medium">最小密码长度</label>
                  <Input
                    type="number"
                    min={6}
                    value={security.minPasswordLength}
                    onChange={(e) =>
                      setSecurity((s) => ({
                        ...s,
                        minPasswordLength: Number(e.target.value),
                      }))
                    }
                  />
                </div>
                <Button type="submit" disabled={saving === "security"}>
                  {saving === "security" ? "保存中…" : "保存安全设置"}
                </Button>
              </form>
            </CardContent>
          </Card>
        </Tabs.Content>
      </Tabs.Root>
    </div>
  );
}

// piano-room-vue3/src/views/admin/settings/Index.vue
<template>
  <div class="admin-page">
    <h2 class="page-title">系统设置</h2>
    <el-tabs v-model="activeTab">
      <el-tab-pane label="基础设置" name="basic">
        <el-card shadow="never">
          <el-form ref="basicFormRef" :model="basicForm" label-width="110px">
            <el-form-item label="系统名称">
              <el-input v-model="basicForm.systemName" clearable style="width:300px" />
            </el-form-item>
            <el-form-item label="联系邮箱">
              <el-input v-model="basicForm.contactEmail" clearable style="width:300px" />
            </el-form-item>
            <el-form-item label="联系电话">
              <el-input v-model="basicForm.contactPhone" clearable style="width:200px" />
            </el-form-item>
            <el-form-item label="公告内容">
              <el-input v-model="basicForm.announcement" type="textarea" :rows="4" style="width:400px" />
            </el-form-item>

            <el-divider content-position="left">时段配置</el-divider>
            <el-form-item label="开放时间起">
              <el-input-number v-model="basicForm.slotStartHour" :min="0" :max="23" style="width:120px" />
              <span class="unit">时（如 8 = 08:00）</span>
            </el-form-item>
            <el-form-item label="开放时间止">
              <el-input-number v-model="basicForm.slotEndHour" :min="1" :max="24" style="width:120px" />
              <span class="unit">时（如 22 = 22:00）</span>
            </el-form-item>
            <el-form-item label="每段时长">
              <el-input-number v-model="basicForm.slotDurationMinutes" :min="30" :max="240" :step="30" style="width:120px" />
              <span class="unit">分钟</span>
            </el-form-item>
            <el-form-item label="每日放开预约时间">
              <el-input-number v-model="basicForm.bookingResetHour" :min="0" :max="23" style="width:120px" />
              <span class="unit">时起可预约次日（0 = 午夜）</span>
            </el-form-item>

            <el-form-item>
              <el-button type="primary" :loading="saving" @click="saveBasic">保存</el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </el-tab-pane>

      <el-tab-pane label="预约设置" name="reservation">
        <el-card shadow="never">
          <el-form label-width="160px">
            <el-form-item label="最长提前预约天数">
              <el-input-number v-model="reservationForm.maxAdvanceDays" :min="1" :max="30" style="width:120px" />
              <span class="unit">天</span>
            </el-form-item>
            <el-form-item label="签到宽限时间">
              <el-input-number v-model="reservationForm.signInGrace" :min="5" :max="60" style="width:120px" />
              <span class="unit">分钟</span>
            </el-form-item>
            <el-form-item label="最大爽约次数">
              <el-input-number v-model="reservationForm.maxNoShow" :min="1" :max="10" style="width:120px" />
              <span class="unit">次</span>
            </el-form-item>
            <el-form-item>
              <el-button type="primary" :loading="saving" @click="saveReservation">保存</el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </el-tab-pane>

      <el-tab-pane label="安全设置" name="security">
        <el-card shadow="never">
          <el-form label-width="160px">
            <el-form-item label="Token 有效期">
              <el-input-number v-model="securityForm.tokenExpireHours" :min="1" :max="720" style="width:120px" />
              <span class="unit">小时</span>
            </el-form-item>
            <el-form-item label="密码最小长度">
              <el-input-number v-model="securityForm.minPasswordLength" :min="6" :max="20" style="width:120px" />
              <span class="unit">位</span>
            </el-form-item>
            <el-form-item>
              <el-button type="primary" :loading="saving" @click="saveSecurity">保存</el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </el-tab-pane>

      <!-- 惩罚规则管理 -->
      <el-tab-pane label="惩罚规则" name="penalty">
        <el-card shadow="never">
          <template #header>
            <div class="penalty-header">
              <span>阶梯惩罚规则配置</span>
              <span class="penalty-tip">管理员可调整各等级的封禁天数（0=仅警告）</span>
            </div>
          </template>
          <el-skeleton v-if="penaltyLoading" :rows="3" animated />
          <el-table v-else :data="penaltyRules" border>
            <el-table-column label="违约次数阈值" prop="violationCount" width="120">
              <template #default="{ row }">
                <el-tag type="danger" size="small">第 {{ row.violationCount }} 次</el-tag>
              </template>
            </el-table-column>
            <el-table-column label="封禁天数" prop="banDays" width="180">
              <template #default="{ row }">
                <div class="ban-edit-row">
                  <el-input-number
                    v-model="row.banDays"
                    :min="0"
                    :max="365"
                    size="small"
                    style="width:120px"
                  />
                  <span class="unit">天</span>
                  <span v-if="row.banDays === 0" class="warn-tip">（仅警告）</span>
                </div>
              </template>
            </el-table-column>
            <el-table-column label="规则说明" prop="description" min-width="200">
              <template #default="{ row }">
                <el-input v-model="row.description" size="small" clearable />
              </template>
            </el-table-column>
            <el-table-column label="操作" width="100">
              <template #default="{ row }">
                <el-button
                  size="small"
                  type="primary"
                  :loading="row._saving"
                  @click="savePenaltyRule(row)"
                >保存</el-button>
              </template>
            </el-table-column>
          </el-table>
        </el-card>
      </el-tab-pane>
    </el-tabs>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import request from '@/utils/request'
import { useSettingsStore } from '@/stores/settings'

const activeTab = ref('basic')
const saving = ref(false)
const penaltyLoading = ref(false)
const penaltyRules = ref<any[]>([])
const settingsStore = useSettingsStore()

const basicForm = reactive({
  systemName: '',
  contactEmail: '',
  contactPhone: '',
  announcement: '',
  slotStartHour: 8,
  slotEndHour: 22,
  slotDurationMinutes: 120,
  bookingResetHour: 0,
})

const reservationForm = reactive({
  maxAdvanceDays: 7,
  signInGrace: 10,
  maxNoShow: 3,
})

const securityForm = reactive({
  tokenExpireHours: 24,
  minPasswordLength: 6,
})

async function loadSettings() {
  try {
    const res = await request.get('/system/settings/basic')
    if (res?.code === 1 && res.data) {
      Object.assign(basicForm, {
        systemName: res.data.systemName || '',
        contactEmail: res.data.contactEmail || '',
        contactPhone: res.data.contactPhone || '',
        announcement: res.data.announcement || '',
        slotStartHour: res.data.slotStartHour ?? 8,
        slotEndHour: res.data.slotEndHour ?? 22,
        slotDurationMinutes: res.data.slotDurationMinutes ?? 120,
        bookingResetHour: res.data.bookingResetHour ?? 0,
      })
    }
  } catch { /* 静默 */ }
}

async function saveBasic() {
  saving.value = true
  try {
    const res = await request.post('/system/settings/basic', basicForm)
    if (res?.code === 1) {
      settingsStore.setBasicSettings(basicForm as any)
      ElMessage.success('保存成功')
    } else ElMessage.error(res?.msg || '保存失败')
  } finally { saving.value = false }
}

async function saveReservation() {
  saving.value = true
  try {
    const res = await request.post('/system/settings/reservation', reservationForm)
    if (res?.code === 1) ElMessage.success('保存成功')
    else ElMessage.error(res?.msg || '保存失败')
  } finally { saving.value = false }
}

async function saveSecurity() {
  saving.value = true
  try {
    const res = await request.post('/system/settings/security', securityForm)
    if (res?.code === 1) ElMessage.success('保存成功')
    else ElMessage.error(res?.msg || '保存失败')
  } finally { saving.value = false }
}

async function loadPenaltyRules() {
  penaltyLoading.value = true
  try {
    const res = await request.get('/system/penalty-rules')
    if (res?.code === 1) penaltyRules.value = (res.data || []).map((r: any) => ({ ...r, _saving: false }))
  } catch { /* 静默 */ } finally { penaltyLoading.value = false }
}

async function savePenaltyRule(row: any) {
  row._saving = true
  try {
    const res = await request.put(`/system/penalty-rules/${row.id}`, {
      banDays: row.banDays,
      description: row.description,
    })
    if (res?.code === 1) ElMessage.success('保存成功')
    else ElMessage.error(res?.msg || '保存失败')
  } finally { row._saving = false }
}

onMounted(() => {
  loadSettings()
  loadPenaltyRules()
})
</script>

<style scoped>
.admin-page { }
.page-title { font-size: 20px; color: var(--color-text); margin-bottom: 16px; font-weight: 700; }
.unit { margin-left: 8px; color: var(--color-text-muted); font-size: 13px; }
.penalty-header { display: flex; align-items: center; justify-content: space-between; }
.penalty-tip { font-size: 13px; color: var(--color-text-muted); }
.ban-edit-row { display: flex; align-items: center; gap: 8px; }
.warn-tip { font-size: 12px; color: var(--color-warning); }
</style>
