// jiaxin-room-next/src/app/(admin)/admin/users/page.tsx
"use client";

import { useCallback, useEffect, useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { motion } from "framer-motion";
import { Loader2, Pencil, Plus, Search, ShieldOff, ShieldCheck, Trash2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { del, get, post, put, type PageData } from "@/lib/api";
import { cn } from "@/lib/utils";

interface UserRow {
  id: number;
  username: string;
  realName: string;
  studentId?: string | null;
  email: string;
  phone?: string | null;
  userType: string;
  status: number;
  violationCount: number;
}

const PAGE_SIZE = 10;

const USER_TYPES = [
  { value: "", label: "全部类型" },
  { value: "student", label: "学生" },
  { value: "teacher", label: "教师" },
  { value: "admin", label: "管理员" },
];

function typeLabel(t: string) {
  const m: Record<string, string> = {
    student: "学生",
    teacher: "教师",
    admin: "管理员",
    super_admin: "超级管理员",
  };
  return m[t] ?? t;
}

function typeVariant(t: string): React.ComponentProps<typeof Badge>["variant"] {
  if (t === "teacher") return "default";
  if (t === "admin" || t === "super_admin") return "warning";
  return "secondary";
}

export default function AdminUsersPage() {
  const [userType, setUserType] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>("");
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);
  const [rows, setRows] = useState<UserRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [msg, setMsg] = useState<string | null>(null);
  const [err, setErr] = useState<string | null>(null);

  const [addOpen, setAddOpen] = useState(false);
  const [editOpen, setEditOpen] = useState(false);
  const [editing, setEditing] = useState<UserRow | null>(null);
  const [saving, setSaving] = useState(false);

  const [addForm, setAddForm] = useState({
    username: "",
    password: "",
    realName: "",
    email: "",
    studentId: "",
    userType: "student",
  });

  const [editForm, setEditForm] = useState({
    realName: "",
    email: "",
    phone: "",
    studentId: "",
    userType: "student",
  });

  const load = useCallback(async () => {
    setLoading(true);
    setErr(null);
    try {
      const statusParam =
        statusFilter === "" ? undefined : Number(statusFilter);
      const res = await get<PageData<UserRow>>("/user/list", {
        page,
        pageSize: PAGE_SIZE,
        userType: userType || undefined,
        status: statusParam,
        usernameOrRealNameOrStudentId: search.trim() || undefined,
      });
      if (res.code === 1 && res.data) {
        setTotal(Number(res.data.total));
        setRows(res.data.rows ?? []);
      } else {
        setErr(res.msg || "加载失败");
        setRows([]);
        setTotal(0);
      }
    } catch {
      setErr("网络错误");
      setRows([]);
      setTotal(0);
    } finally {
      setLoading(false);
    }
  }, [page, userType, statusFilter, search]);

  useEffect(() => {
    load();
  }, [load]);

  useEffect(() => {
    setPage(1);
  }, [userType, statusFilter, search]);

  function openEdit(u: UserRow) {
    setEditing(u);
    setEditForm({
      realName: u.realName,
      email: u.email,
      phone: u.phone ?? "",
      studentId: u.studentId ?? "",
      userType: u.userType,
    });
    setEditOpen(true);
  }

  async function submitAdd(e: React.FormEvent) {
    e.preventDefault();
    setSaving(true);
    setErr(null);
    try {
      const res = await post("/user/add", {
        username: addForm.username.trim(),
        password: addForm.password,
        realName: addForm.realName.trim(),
        email: addForm.email.trim(),
        studentId: addForm.studentId.trim() || undefined,
        userType: addForm.userType,
      });
      if (res.code === 1) {
        setMsg("用户已创建");
        setAddOpen(false);
        setAddForm({
          username: "",
          password: "",
          realName: "",
          email: "",
          studentId: "",
          userType: "student",
        });
        load();
      } else setErr(res.msg || "创建失败");
    } catch {
      setErr("创建失败");
    } finally {
      setSaving(false);
    }
  }

  async function submitEdit(e: React.FormEvent) {
    e.preventDefault();
    if (!editing) return;
    setSaving(true);
    setErr(null);
    try {
      const res = await put("/user/info", {
        id: editing.id,
        username: editing.username,
        realName: editForm.realName.trim(),
        email: editForm.email.trim(),
        phone: editForm.phone.trim() || null,
        studentId: editForm.studentId.trim() || null,
        userType: editForm.userType,
      });
      if (res.code === 1) {
        setMsg("资料已更新");
        setEditOpen(false);
        load();
      } else setErr(res.msg || "保存失败");
    } catch {
      setErr("保存失败");
    } finally {
      setSaving(false);
    }
  }

  async function setUserStatus(u: UserRow, next: number) {
    setErr(null);
    try {
      const res = await post("/user/status", { userId: u.id, status: next });
      if (res.code === 1) {
        setMsg(next === 1 ? "已启用" : "已禁用");
        load();
      } else setErr(res.msg || "操作失败");
    } catch {
      setErr("操作失败");
    }
  }

  async function removeUser(u: UserRow) {
    if (!confirm(`确定删除用户「${u.username}」？此操作不可恢复。`)) return;
    setErr(null);
    try {
      const res = await del("/user", { ids: [u.id] });
      if (res.code === 1) {
        setMsg("已删除");
        load();
      } else setErr(res.msg || "删除失败");
    } catch {
      setErr("删除失败");
    }
  }

  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));

  return (
    <div className="space-y-6">
      <motion.div
        initial={{ opacity: 0, y: 6 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"
      >
        <div>
          <h1 className="text-xl font-semibold tracking-tight text-[var(--color-text)]">
            用户管理
          </h1>
          <p className="mt-1 text-sm text-[var(--color-text-secondary)]">
            检索、创建与账号状态维护
          </p>
        </div>
        <Button type="button" className="shadow-[var(--shadow-sm)]" onClick={() => setAddOpen(true)}>
          <Plus className="size-4" />
          新增用户
        </Button>
      </motion.div>

      {msg ? (
        <p className="rounded-[var(--radius-md)] bg-[var(--color-success-bg)] px-3 py-2 text-sm text-[var(--color-success)]">
          {msg}
        </p>
      ) : null}
      {err ? (
        <p className="rounded-[var(--radius-md)] bg-[var(--color-danger-bg)] px-3 py-2 text-sm text-[var(--color-danger)]">
          {err}
        </p>
      ) : null}

      <Card className="border-[var(--color-border-light)] bg-white shadow-[var(--shadow-card)]">
        <CardHeader className="pb-4">
          <CardTitle className="text-base font-medium">筛选</CardTitle>
          <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:flex-wrap">
            <select
              className="h-10 min-w-[8rem] rounded-[var(--radius-sm)] border border-[var(--color-border)] bg-white px-3 text-sm"
              value={userType}
              onChange={(e) => setUserType(e.target.value)}
            >
              {USER_TYPES.map((o) => (
                <option key={o.value || "all"} value={o.value}>
                  {o.label}
                </option>
              ))}
            </select>
            <select
              className="h-10 min-w-[8rem] rounded-[var(--radius-sm)] border border-[var(--color-border)] bg-white px-3 text-sm"
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
            >
              <option value="">全部状态</option>
              <option value="1">正常</option>
              <option value="0">禁用</option>
            </select>
            <div className="relative min-w-[200px] flex-1">
              <Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[var(--color-text-tertiary)]" />
              <Input
                className="h-10 pl-9"
                placeholder="用户名 / 姓名 / 学号"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <table className="w-full min-w-[1040px] text-left text-sm">
              <thead className="border-y border-[var(--color-divider)] bg-[var(--color-bg-tertiary)]/60 text-[var(--color-text-secondary)]">
                <tr>
                  <th className="px-4 py-3 font-medium">用户名</th>
                  <th className="px-4 py-3 font-medium">姓名</th>
                  <th className="px-4 py-3 font-medium">学号</th>
                  <th className="px-4 py-3 font-medium">类型</th>
                  <th className="px-4 py-3 font-medium">状态</th>
                  <th className="px-4 py-3 font-medium">违约次数</th>
                  <th className="px-4 py-3 font-medium text-right">操作</th>
                </tr>
              </thead>
              <tbody>
                {loading ? (
                  <tr>
                    <td colSpan={7} className="px-4 py-16 text-center">
                      <Loader2 className="mx-auto size-6 animate-spin text-[var(--color-primary)]" />
                    </td>
                  </tr>
                ) : rows.length === 0 ? (
                  <tr>
                    <td
                      colSpan={7}
                      className="px-4 py-12 text-center text-[var(--color-text-tertiary)]"
                    >
                      暂无数据
                    </td>
                  </tr>
                ) : (
                  rows.map((u) => (
                    <tr
                      key={u.id}
                      className="border-b border-[var(--color-divider)]/80 transition-colors hover:bg-[var(--color-bg-secondary)]/50 last:border-0"
                    >
                      <td className="px-4 py-3.5 font-medium text-[var(--color-text)]">
                        {u.username}
                      </td>
                      <td className="px-4 py-3.5 text-[var(--color-text)]">{u.realName}</td>
                      <td className="px-4 py-3.5 font-mono text-xs text-[var(--color-text-secondary)]">
                        {u.studentId ?? "—"}
                      </td>
                      <td className="px-4 py-3.5">
                        <Badge variant={typeVariant(u.userType)}>
                          {typeLabel(u.userType)}
                        </Badge>
                      </td>
                      <td className="px-4 py-3.5">
                        <span
                          className={cn(
                            "inline-flex rounded-[var(--radius-full)] px-2.5 py-0.5 text-xs font-medium",
                            u.status === 1
                              ? "bg-[var(--color-success-bg)] text-[var(--color-success)]"
                              : "bg-[var(--color-bg-secondary)] text-[var(--color-text-secondary)]"
                          )}
                        >
                          {u.status === 1 ? "正常" : "禁用"}
                        </span>
                      </td>
                      <td className="px-4 py-3.5 tabular-nums text-[var(--color-text-secondary)]">
                        {u.violationCount}
                      </td>
                      <td className="px-4 py-3.5 text-right">
                        <div className="flex flex-wrap justify-end gap-1">
                          <Button
                            type="button"
                            variant="ghost"
                            size="sm"
                            className="text-[var(--color-primary)]"
                            onClick={() => openEdit(u)}
                          >
                            <Pencil className="size-3.5" />
                            编辑
                          </Button>
                          {u.status === 1 ? (
                            <Button
                              type="button"
                              variant="ghost"
                              size="sm"
                              onClick={() => setUserStatus(u, 0)}
                            >
                              <ShieldOff className="size-3.5" />
                              禁用
                            </Button>
                          ) : (
                            <Button
                              type="button"
                              variant="ghost"
                              size="sm"
                              onClick={() => setUserStatus(u, 1)}
                            >
                              <ShieldCheck className="size-3.5" />
                              启用
                            </Button>
                          )}
                          <Button
                            type="button"
                            variant="ghost"
                            size="sm"
                            className="text-[var(--color-danger)]"
                            onClick={() => removeUser(u)}
                          >
                            <Trash2 className="size-3.5" />
                            删除
                          </Button>
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
          <div className="flex flex-col items-center justify-between gap-3 border-t border-[var(--color-divider)] px-4 py-3 sm:flex-row">
            <p className="text-xs text-[var(--color-text-tertiary)]">
              共 {total} 条 · 第 {page} / {totalPages} 页
            </p>
            <div className="flex items-center gap-2">
              <Button
                type="button"
                variant="outline"
                size="sm"
                disabled={page <= 1 || loading}
                onClick={() => setPage((p) => Math.max(1, p - 1))}
              >
                上一页
              </Button>
              <Button
                type="button"
                variant="outline"
                size="sm"
                disabled={page >= totalPages || loading}
                onClick={() => setPage((p) => p + 1)}
              >
                下一页
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      <Dialog.Root open={addOpen} onOpenChange={setAddOpen}>
        <Dialog.Portal>
          <Dialog.Overlay className="fixed inset-0 z-50 bg-black/25 backdrop-blur-[1px]" />
          <Dialog.Content
            className={cn(
              "fixed left-1/2 top-1/2 z-[51] w-[min(100%-2rem,26rem)] -translate-x-1/2 -translate-y-1/2",
              "max-h-[min(90vh,40rem)] overflow-y-auto rounded-[var(--radius-xl)] border border-[var(--color-border-light)] bg-white p-6 shadow-[var(--shadow-lg)]"
            )}
          >
            <Dialog.Title className="text-lg font-semibold">新增用户</Dialog.Title>
            <Dialog.Description className="mt-1 text-sm text-[var(--color-text-secondary)]">
              创建后可使用用户名与密码登录
            </Dialog.Description>
            <form onSubmit={submitAdd} className="mt-6 space-y-4">
              <div className="space-y-1.5">
                <label className="text-sm font-medium">用户名</label>
                <Input
                  required
                  value={addForm.username}
                  onChange={(e) =>
                    setAddForm((f) => ({ ...f, username: e.target.value }))
                  }
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-medium">初始密码</label>
                <Input
                  type="password"
                  required
                  minLength={6}
                  value={addForm.password}
                  onChange={(e) =>
                    setAddForm((f) => ({ ...f, password: e.target.value }))
                  }
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-medium">姓名</label>
                <Input
                  required
                  value={addForm.realName}
                  onChange={(e) =>
                    setAddForm((f) => ({ ...f, realName: e.target.value }))
                  }
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-medium">邮箱</label>
                <Input
                  type="email"
                  required
                  value={addForm.email}
                  onChange={(e) =>
                    setAddForm((f) => ({ ...f, email: e.target.value }))
                  }
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-medium">学号</label>
                <Input
                  value={addForm.studentId}
                  onChange={(e) =>
                    setAddForm((f) => ({ ...f, studentId: e.target.value }))
                  }
                  placeholder="选填"
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-medium">类型</label>
                <select
                  className="flex h-10 w-full rounded-[var(--radius-sm)] border border-[var(--color-border)] bg-white px-3 text-sm"
                  value={addForm.userType}
                  onChange={(e) =>
                    setAddForm((f) => ({ ...f, userType: e.target.value }))
                  }
                >
                  <option value="student">学生</option>
                  <option value="teacher">教师</option>
                </select>
              </div>
              <div className="flex justify-end gap-2 pt-2">
                <Button type="button" variant="outline" onClick={() => setAddOpen(false)}>
                  取消
                </Button>
                <Button type="submit" disabled={saving}>
                  {saving ? "提交中…" : "创建"}
                </Button>
              </div>
            </form>
          </Dialog.Content>
        </Dialog.Portal>
      </Dialog.Root>

      <Dialog.Root open={editOpen} onOpenChange={setEditOpen}>
        <Dialog.Portal>
          <Dialog.Overlay className="fixed inset-0 z-50 bg-black/25 backdrop-blur-[1px]" />
          <Dialog.Content
            className={cn(
              "fixed left-1/2 top-1/2 z-[51] w-[min(100%-2rem,26rem)] -translate-x-1/2 -translate-y-1/2",
              "max-h-[min(90vh,40rem)] overflow-y-auto rounded-[var(--radius-xl)] border border-[var(--color-border-light)] bg-white p-6 shadow-[var(--shadow-lg)]"
            )}
          >
            <Dialog.Title className="text-lg font-semibold">编辑用户</Dialog.Title>
            <Dialog.Description className="mt-1 text-sm text-[var(--color-text-secondary)]">
              {editing ? `ID ${editing.id} · ${editing.username}` : ""}
            </Dialog.Description>
            <form onSubmit={submitEdit} className="mt-6 space-y-4">
              <div className="space-y-1.5">
                <label className="text-sm font-medium">姓名</label>
                <Input
                  required
                  value={editForm.realName}
                  onChange={(e) =>
                    setEditForm((f) => ({ ...f, realName: e.target.value }))
                  }
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-medium">邮箱</label>
                <Input
                  type="email"
                  required
                  value={editForm.email}
                  onChange={(e) =>
                    setEditForm((f) => ({ ...f, email: e.target.value }))
                  }
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-medium">手机</label>
                <Input
                  value={editForm.phone}
                  onChange={(e) =>
                    setEditForm((f) => ({ ...f, phone: e.target.value }))
                  }
                  placeholder="选填"
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-medium">学号</label>
                <Input
                  value={editForm.studentId}
                  onChange={(e) =>
                    setEditForm((f) => ({ ...f, studentId: e.target.value }))
                  }
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-medium">类型</label>
                <select
                  className="flex h-10 w-full rounded-[var(--radius-sm)] border border-[var(--color-border)] bg-white px-3 text-sm"
                  value={editForm.userType}
                  onChange={(e) =>
                    setEditForm((f) => ({ ...f, userType: e.target.value }))
                  }
                >
                  <option value="student">学生</option>
                  <option value="teacher">教师</option>
                  <option value="admin">管理员</option>
                </select>
              </div>
              <div className="flex justify-end gap-2 pt-2">
                <Button type="button" variant="outline" onClick={() => setEditOpen(false)}>
                  取消
                </Button>
                <Button type="submit" disabled={saving}>
                  {saving ? "保存中…" : "保存"}
                </Button>
              </div>
            </form>
          </Dialog.Content>
        </Dialog.Portal>
      </Dialog.Root>
    </div>
  );
}

// piano-room-vue3/src/views/admin/users/Index.vue
<template>
  <div class="admin-page">
    <div class="page-header">
      <h2>用户管理</h2>
      <div class="header-actions">
        <el-button type="success" :icon="Download" @click="handleExport">导出 Excel</el-button>
        <el-button type="primary" :icon="Plus" @click="openAddDialog">添加用户</el-button>
      </div>
    </div>

    <!-- 搜索栏 -->
    <el-card class="search-card" shadow="never">
      <el-form :model="query" inline>
        <el-form-item label="关键词">
          <el-input v-model="query.usernameOrRealNameOrStudentId" placeholder="用户名/姓名/学号" clearable @keyup.enter="loadData" />
        </el-form-item>
        <el-form-item label="用户类型">
          <el-select v-model="query.userType" clearable placeholder="全部" style="width: 120px">
            <el-option label="学生" value="student" />
            <el-option label="教师" value="teacher" />
            <el-option label="管理员" value="admin" />
            <el-option label="超级管理员" value="super_admin" />
          </el-select>
        </el-form-item>
        <el-form-item label="状态">
          <el-select v-model="query.status" clearable placeholder="全部" style="width: 100px">
            <el-option label="正常" :value="1" />
            <el-option label="禁用" :value="0" />
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" :icon="Search" @click="loadData">搜索</el-button>
          <el-button :icon="Refresh" @click="resetQuery">重置</el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <!-- 数据表格 -->
    <el-card class="table-card" shadow="never">
      <el-table v-loading="loading" :data="tableData" stripe border row-key="id">
        <el-table-column label="用户名" prop="username" min-width="110" />
        <el-table-column label="真实姓名" prop="realName" min-width="100" />
        <el-table-column label="学号" prop="studentId" min-width="120" />
        <el-table-column label="邮箱" prop="email" min-width="160" />
        <el-table-column label="用户类型" prop="userType" width="120">
          <template #default="{ row }">
            <el-tag :type="userTypeColor(row.userType)" size="small">{{ userTypeLabel(row.userType) }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="违约次数" prop="violationCount" width="90">
          <template #default="{ row }">
            <el-tag v-if="row.violationCount > 0" size="small" type="danger">
              {{ row.violationCount }} 次
            </el-tag>
            <span v-else class="text-muted">0</span>
          </template>
        </el-table-column>
        <el-table-column label="封禁状态" width="130">
          <template #default="{ row }">
            <div v-if="row.banUntil && new Date(row.banUntil) > new Date()">
              <el-tag size="small" type="danger">封禁中</el-tag>
              <div style="font-size:11px;color:#94a3b8;margin-top:2px">
                至 {{ row.banUntil?.substring(0, 10) }}
              </div>
            </div>
            <span v-else class="text-muted">—</span>
          </template>
        </el-table-column>
        <el-table-column label="状态" prop="status" width="80">
          <template #default="{ row }">
            <el-switch
              :model-value="row.status === 1"
              @change="(val: string | number | boolean) => handleStatusChange(row, Boolean(val))"
            />
          </template>
        </el-table-column>
        <el-table-column label="最后登录" prop="lastLoginTime" min-width="150" />
        <el-table-column label="操作" width="240" fixed="right" class-name="action-col">
          <template #default="{ row }">
            <div class="action-wrapper">
              <div class="action-card">
                <button class="action-btn" @click="handleEdit(row)">
                  <el-icon size="14"><Edit /></el-icon>
                  <span>编辑</span>
                </button>
                <button class="action-btn" @click="handleResetPwd(row)">
                  <el-icon size="14"><Key /></el-icon>
                  <span>重置密码</span>
                </button>
                <button
                  v-if="row.banUntil && new Date(row.banUntil) > new Date()"
                  class="action-btn warn"
                  @click="handleRemoveBan(row)"
                >
                  <el-icon size="14"><Unlock /></el-icon>
                  <span>解除封禁</span>
                </button>
                <button class="action-btn danger" @click="handleDelete(row)">
                  <el-icon size="14"><Delete /></el-icon>
                  <span>删除</span>
                </button>
              </div>
            </div>
          </template>
        </el-table-column>
      </el-table>
      <el-pagination
        v-model:current-page="query.page"
        v-model:page-size="query.pageSize"
        :total="total"
        :page-sizes="[10, 20, 50]"
        layout="total, sizes, prev, pager, next"
        class="pagination"
        @change="loadData"
      />
    </el-card>

    <!-- 添加/编辑用户弹窗 -->
    <el-dialog v-model="dialogVisible" :title="editingUser ? '编辑用户' : '添加用户'" width="500px">
      <el-form ref="formRef" :model="form" :rules="formRules" label-width="90px">
        <el-form-item label="用户名" prop="username">
          <el-input v-model="form.username" :disabled="!!editingUser" clearable />
        </el-form-item>
        <el-form-item v-if="!editingUser" label="密码" prop="password">
          <el-input v-model="form.password" type="password" show-password clearable />
        </el-form-item>
        <el-form-item label="真实姓名" prop="realName">
          <el-input v-model="form.realName" clearable />
        </el-form-item>
        <el-form-item label="学号" prop="studentId">
          <el-input v-model="form.studentId" clearable />
        </el-form-item>
        <el-form-item label="邮箱" prop="email">
          <el-input v-model="form.email" clearable />
        </el-form-item>
        <el-form-item label="手机号" prop="phone">
          <el-input v-model="form.phone" clearable />
        </el-form-item>
        <el-form-item label="用户类型" prop="userType">
          <el-select v-model="form.userType" style="width: 100%">
            <el-option label="学生" value="student" />
            <el-option label="教师" value="teacher" />
            <el-option label="管理员" value="admin" />
          </el-select>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" :loading="submitting" @click="handleSubmit">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox, type FormInstance, type FormRules } from 'element-plus'
import { Plus, Search, Refresh, Download, Edit, Key, Delete, Unlock } from '@element-plus/icons-vue'
import { userApi } from '@/api/user'
import { exportApi, downloadBlob } from '@/api/export'
import request from '@/utils/request'
import type { User } from '@/api/types'

const loading = ref(false)
const submitting = ref(false)
const tableData = ref<User[]>([])
const total = ref(0)
const dialogVisible = ref(false)
const editingUser = ref<User | null>(null)
const formRef = ref<FormInstance>()

const query = reactive({
  page: 1,
  pageSize: 10,
  userType: '',
  status: undefined as number | undefined,
  usernameOrRealNameOrStudentId: '',
})

const form = reactive({
  username: '',
  password: '',
  realName: '',
  studentId: '',
  email: '',
  phone: '',
  userType: 'student',
})

const formRules: FormRules = {
  username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
  password: [{ required: true, min: 6, message: '密码至少6位', trigger: 'blur' }],
  realName: [{ required: true, message: '请输入真实姓名', trigger: 'blur' }],
  userType: [{ required: true, message: '请选择用户类型', trigger: 'change' }],
}

const userTypeLabel = (type: string) => {
  const map: Record<string, string> = { student: '学生', teacher: '教师', admin: '管理员', super_admin: '超管' }
  return map[type] || type
}

type TagType = 'primary' | 'success' | 'warning' | 'info' | 'danger' | undefined
const userTypeColor = (type: string): TagType => {
  const map: Record<string, TagType> = { student: undefined, teacher: 'success', admin: 'warning', super_admin: 'danger' }
  return map[type]
}

async function loadData() {
  loading.value = true
  try {
    const res = await userApi.list(query)
    if (res?.code === 1) {
      tableData.value = res.data?.rows || []
      total.value = res.data?.total || 0
    }
  } finally {
    loading.value = false
  }
}

function resetQuery() {
  query.page = 1
  query.usernameOrRealNameOrStudentId = ''
  query.userType = ''
  query.status = undefined
  loadData()
}

function openAddDialog() {
  editingUser.value = null
  Object.assign(form, { username: '', password: '', realName: '', studentId: '', email: '', phone: '', userType: 'student' })
  dialogVisible.value = true
}

function handleEdit(row: User) {
  editingUser.value = row
  Object.assign(form, { username: row.username, realName: row.realName, studentId: row.studentId, email: row.email, phone: row.phone, userType: row.userType })
  dialogVisible.value = true
}

async function handleSubmit() {
  await formRef.value?.validate(async (valid) => {
    if (!valid) return
    submitting.value = true
    try {
      if (editingUser.value) {
        await userApi.update({ ...form, id: editingUser.value.id })
        ElMessage.success('更新成功')
      } else {
        await userApi.addUser(form as any)
        ElMessage.success('添加成功')
      }
      dialogVisible.value = false
      loadData()
    } finally {
      submitting.value = false
    }
  })
}

async function handleStatusChange(row: User, val: boolean) {
  await userApi.setStatus(row.id, val ? 1 : 0)
  row.status = val ? 1 : 0
  ElMessage.success('状态更新成功')
}

async function handleResetPwd(row: User) {
  const result = await ElMessageBox.prompt(`重置用户 "${row.username}" 的密码`, '重置密码', {
    confirmButtonText: '确定',
    cancelButtonText: '取消',
    inputPlaceholder: '请输入新密码（至少6位）',
    inputValidator: (v) => v && v.length >= 6 ? true : '密码至少6位',
  })
  const newPwd = String((result as any).value ?? '')
  await userApi.resetPassword({ id: row.id, newPassword: newPwd, againPassword: newPwd })
  ElMessage.success('密码重置成功')
}

async function handleDelete(row: User) {
  await ElMessageBox.confirm(`确定删除用户 "${row.username}" 吗？`, '确认删除', { type: 'warning' })
  await userApi.delete([row.id])
  ElMessage.success('删除成功')
  loadData()
}

async function handleRemoveBan(row: User) {
  await ElMessageBox.confirm(`确定解除用户 "${row.username}" 的封禁？`, '确认', { type: 'warning' })
  try {
    await request.delete(`/system/penalty-rules/ban/${row.id}`)
    ElMessage.success('已解除封禁')
    loadData()
  } catch {
    ElMessage.error('操作失败')
  }
}

async function handleExport() {
  try {
    const blob = await exportApi.exportUsers({
      keyword: query.usernameOrRealNameOrStudentId,
      userType: query.userType,
    })
    downloadBlob(blob as any, `用户列表_${new Date().toLocaleDateString()}.xlsx`)
    ElMessage.success('导出成功')
  } catch {
    ElMessage.error('导出失败')
  }
}

onMounted(() => loadData())
</script>

<style scoped>
.admin-page { }
.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}
.page-header h2 { font-size: 20px; color: #303133; }
.header-actions { display: flex; gap: 8px; }
.search-card { margin-bottom: 16px; }
.table-card { }
.pagination { margin-top: 16px; display: flex; justify-content: flex-end; }

/* ===== 操作列样式（始终可见） ===== */
:deep(.action-col) { overflow: visible; }
:deep(.action-col .cell) { overflow: visible; padding: 0 8px; }

.action-wrapper {
  opacity: 1;
  display: flex;
  align-items: center;
}

.action-card {
  background: #fff;
  border: 1px solid #e4e7ed;
  border-radius: 8px;
  padding: 4px 6px;
  display: flex;
  gap: 4px;
  flex-wrap: wrap;
  width: 100%;
}

.action-btn {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 4px 8px;
  border-radius: 6px;
  font-size: 13px;
  color: #606266;
  background: transparent;
  border: none;
  cursor: pointer;
  transition: all 0.2s;
  white-space: nowrap;
}
.action-btn:hover {
  background: #f5f7fa;
  color: #409eff;
}
.action-btn.danger:hover {
  background: #fef0f0;
  color: #f56c6c;
}
.action-btn.warn:hover {
  background: #fef3c7;
  color: #f59e0b;
}
.text-muted { color: #94a3b8; font-size: 13px; }

</style>
